from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

import numpy as np
import pandas as pd

from sqlalchemy import select, func
from sqlalchemy.orm import Session

from ..backtest.engine import run_backtest, Trade, BacktestResult
from ..models import BacktestRunRow, StrategyFitRow, TrialsRow, PositionRow
from ..risk.engine import RiskEngine, RiskConfig


def _window_bounds(
    history_start: datetime,
    history_end: datetime,
    train_years: float = 3.0,
    test_years: float = 1.0,
    step_years: float = 1.0,
    embargo_years: float | None = None,
) -> list[dict[str, Any]]:
    """Generate rolling window bounds for walk-forward validation.

    Returns a list of dicts with keys: train_start, train_end, test_start, test_end.
    Windows are generated by stepping forward by step_years after each iteration.
    Embargo period after each test window defaults to the longest trade holding time
    (if embargo_years is None, we use a sensible default of 0.5 years).
    """
    # Parse boundaries
    start = history_start.replace(tzinfo=None) if history_start.tzinfo else history_start
    end = history_end.replace(tzinfo=None) if history_end.tzinfo else history_end

    train_duration = timedelta(days=int(train_years * 365))
    test_duration = timedelta(days=int(test_years * 365))
    step_duration = timedelta(days=int(step_years * 365))
    embargo_duration = timedelta(days=int((embargo_years or 0.5) * 365))

    windows: list[dict[str, Any]] = []
    train_start = start

    while train_start + train_duration + test_duration <= end:
        train_end = train_start + train_duration
        test_start = train_end
        test_end = test_start + test_duration

        # Apply embargo: after the test window, skip ahead by embargo_duration
        # before the next training window begins
        next_train_start = test_end + embargo_duration

        windows.append(
            {
                "train_start": train_start.isoformat(),
                "train_end": train_end.isoformat(),
                "test_start": test_start.isoformat(),
                "test_end": test_end.isoformat(),
                "next_train_start": next_train_start.isoformat()
                if next_train_start <= end
                else None,
            }
        )

        # Move to the next window
        if next_train_start is None or next_train_start >= end:
            break
        train_start = next_train_start

    return windows


def walkforward_validate(
    session: Session,
    strategy_name: str,
    symbol: str,
    *,
    timeframe: str = "1d",
    capital: float = 100_000.0,
    param_grid: list[dict[str, Any]] | None = None,
    train_years: float = 3.0,
    test_years: float = 1.0,
    step_years: float = 1.0,
    embargo_years: float | None = None,
    cost_model: Any | None = None,
    slippage_bps: float = 5.0,
) -> dict[str, Any]:
    """Run walk-forward validation for a strategy/symbol pair.

    For each window:
    1. Train on the training slice using the param grid, picking the best
       by lower confidence bound of expectancy in R.
    2. Apply the best preset to the test window and record out-of-sample trades.
    3. Count every grid point in the trial registry.

    Returns a dict with window results, selected parameters, and out-of-sample metrics.
    """
    from ..data.sources import get_source
    from ..data.base import DataProvider
    from ..db import make_engine, make_session_factory

    # Get historical price data
    provider = DataProvider(make_session_factory(make_engine("sqlite:///tradelite.db")))
    df = provider.get_bars(symbol, timeframe)

    if len(df) < 365:
        return {"error": f"Insufficient history for walk-forward: {len(df)} bars"}

    windows = _window_bounds(
        history_start=df.index[0],
        history_end=df.index[-1],
        train_years=train_years,
        test_years=test_years,
        step_years=step_years,
        embargo_years=embargo_years,
    )

    if not windows:
        return {"error": "No valid windows generated"}

    # Collect results across all windows
    all_oos_trades: list[dict[str, Any]] = []
    window_results: list[dict[str, Any]] = []
    selected_params_per_window: list[dict[str, Any]] = []

    for window in windows:
        # --- Train phase ---
        train_mask = (df.index >= window["train_start"]) & (df.index <= window["train_end"])
        train_df = df.loc[train_mask]

        if len(train_df) < 365:
            continue

        best_r = -float("inf")
        best_params: dict[str, Any] | None = None
        best_ci_low = -float("inf")

        # If no param grid specified, use default parameters from strategy registry
        grid = param_grid or [{}]

        for params in grid:
            # Run backtest on training data only
            try:
                res = run_backtest(
                    strategy_name,
                    train_df,
                    symbol,
                    capital=capital,
                    cost_model=cost_model,
                    slippage_bps=slippage_bps,
                )
                # Get expectancy in R and its CI
                r_vals = [t.r_multiple for t in res.trades if t.r_multiple is not None]
                if not r_vals:
                    continue
                mean_r = float(np.mean(r_vals))
                # Simple CI: mean +/- 2*std/sqrt(n) (quick approximation)
                n = len(r_vals)
                ci_low = mean_r - 2 * float(np.std(r_vals, ddof=1)) / np.sqrt(n) if n > 1 else mean_r

                if ci_low > best_ci_low:
                    best_ci_low = ci_low
                    best_params = params
                    best_r = mean_r
            except Exception:
                continue

        # --- Test phase ---
        if best_params is None:
            # Fallback: use default params
            best_params = {}

        test_mask = (df.index >= window["test_start"]) & (df.index <= window["test_end"])
        test_df = df.loc[test_mask]

        if len(test_df) < 30:
            continue

        try:
            res = run_backtest(
                strategy_name,
                test_df,
                symbol,
                capital=capital,
                cost_model=cost_model,
                slippage_bps=slippage_bps,
                **best_params,
            )
        except Exception:
            continue

        # Record the out-of-sample trades
        oos_trades = [
            {
                "symbol": t.symbol,
                "strategy": t.strategy,
                "side": t.side,
                "entry_ts": t.entry_ts.isoformat(),
                "exit_ts": t.exit_ts.isoformat(),
                "entry_price": t.entry_price,
                "exit_price": t.exit_price,
                "qty": t.qty,
                "net_pnl": t.net_pnl,
                "r_multiple": t.r_multiple,
                "reason": t.reason,
            }
            for t in res.trades
        ]

        # Record the trial
        # Count every grid point tried
        for params in grid:
            _record_trial(
                session,
                strategy_name,
                symbol,
                params,
                window["test_start"],
                res.metrics["n_trades"],
                res.metrics["expectancy"],
            )

        n_oos_trades = res.metrics["n_trades"]
        oos_expectancy = res.metrics["expectancy"]

        window_results.append(
            {
                "window": len(window_results) + 1,
                "train_start": window["train_start"],
                "test_start": window["test_start"],
                "test_end": window["test_end"],
                "selected_params": best_params,
                "n_oos_trades": n_oos_trades,
                "oos_expectancy": oos_expectancy,
                "oos_ci_low": res.ci_low,
                "oos_ci_high": res.ci_high,
            }
        )
        selected_params_per_window.append(best_params or {})
        all_oos_trades.extend(oos_trades)

    # Compute overall out-of-sample metrics
    overall_metrics = {}
    if all_oos_trades:
        all_r = [t["r_multiple"] for t in all_oos_trades if t["r_multiple"] is not None]
        if all_r:
            overall_metrics = {
                "n_total_oos_trades": len(all_oos_trades),
                "mean_r_multiple": float(np.mean(all_r)),
                "ci_low": float(np.percentile(all_r, 2.5)),
                "ci_high": float(np.percentile(all_r, 97.5)),
            }

    return {
        "windows": window_results,
        "selected_params": selected_params_per_window,
        "overall_metrics": overall_metrics,
        "n_windows": len(window_results),
        "trial_count": session.scalar(
            select(func.count()).select_from(TrialsRow).where(
                TrialsRow.strategy == strategy_name,
                TrialsRow.symbol == symbol,
            )
        )
        if "trial_count" in str(type(session))
        else 0,
    }


def _record_trial(
    session: Session,
    strategy: str,
    symbol: str,
    params: dict[str, Any] | None,
    run_at: str,
    n_trades: int,
    expectancy: float | None,
) -> None:
    """Record a trial entry in the trials table for multiple-testing control."""
    from hashlib import sha256
    import datetime

    params_hash = sha256(str(sorted(params or {})).encode()).hexdigest() if params else sha256(b"default").hexdigest()
    run_dt = datetime.datetime.fromisoformat(run_at) if isinstance(run_at, str) else run_at

    trial = session.scalar(
        select(TrialsRow).where(
            TrialsRow.strategy == strategy,
            TrialsRow.symbol == symbol,
            TrialsRow.params_hash == params_hash,
            TrialsRow.run_at == run_dt,
        )
    )
    if trial is None:
        trial = TrialsRow(
            strategy=strategy,
            symbol=symbol,
            params_hash=params_hash,
            run_at=run_dt,
            n_trades=n_trades,
            expectancy=expectancy,
        )
        session.add(trial)
    else:
        trial.n_trades += n_trades
        if trial.expectancy is not None and expectancy is not None:
            trial.expectancy = (trial.expectancy + expectancy) / 2
        elif expectancy is not None:
            trial.expectancy = expectancy
    session.commit()